---
title: "Citibike"
author: "Charles Lang"
date: "October 27, 2016"
output: html_document
---
#Load libraries
```{r}
library(dplyr)
library(tidyr)
library(igraph)
```
#Load in the data
```{r}
D1 <- read.csv("2013-07 - Citi Bike trip data.csv", header = TRUE)
```
#Data manipulation
```{r}
D1$starttime <- as.POSIXct(D1$starttime, tz = "EST")

D2 <- filter(D1, starttime >= "2013-07-01 00:00:00" & starttime <= "2013-07-01 23:59:59")

EDGE <- select(D2, start.station.id, end.station.id)
EDGE$count <- 1

EDGE <- EDGE %>% group_by(start.station.id, end.station.id) %>% summarise(sum(count))

names(EDGE) <- c("to", "from", "count")

START <- as.data.frame(EDGE$from)
names(START) <- c("station")

END <- as.data.frame(EDGE$to)
names(END) <- c("station")

VERT <- rbind(START, END)

VERT <- unique(VERT)
```
#Plot graph
```{r}
g <- graph.data.frame(EDGE, directed=TRUE, vertices=VERT)

plot(g,layout=layout_with_fr(g),
    vertex.size=1.5,
    edge.arrow.size=0.05, 
    vertex.label="",
    edge.width = EDGE$count*0.1)

#Calculate degree
VERT$degree <- degree(g)
     
D3 <- filter(D1, start.station.id == 519)
D3 <- filter(D1, start.station.id == 497)

```

